// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Mendapatkan konfigurasi [FirebaseOptions] yang sesuai dengan platform target aktif (Android, iOS, atau Web).
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ9zAbZ4EIHcb1SwvTE9n06dVvoy0TQpc',
    appId: '1:309930970714:android:d9a55e472b39a534e15263',
    messagingSenderId: '309930970714',
    projectId: 'go-sampah-v2-baru',
    storageBucket: 'go-sampah-v2-baru.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcc466cK3Ls4_2t3ssnyqOB1P27QtETa8',
    appId: '1:309930970714:ios:a504c83cc33559bde15263',
    messagingSenderId: '309930970714',
    projectId: 'go-sampah-v2-baru',
    storageBucket: 'go-sampah-v2-baru.firebasestorage.app',
    iosBundleId: 'com.gosampah.goSampahV2',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcIF6uXL2UkROyWJcftcjgZNMDVqDRtK4',
    appId: '1:309930970714:web:8cf14a866433608ee15263',
    messagingSenderId: '309930970714',
    projectId: 'go-sampah-v2-baru',
    authDomain: 'go-sampah-v2-baru.firebaseapp.com',
    storageBucket: 'go-sampah-v2-baru.firebasestorage.app',
    measurementId: 'G-NW5WZJX82G',
  );
}
